let stockProductos =[
    {id: 1, clase: "Vinos", producto: "Vino", tipo: "Malbec", desc: "Vino tinto Malbec Cafayate Reserve bodega Etchart 750 ml", precio: 800, img: 'img/productos/01.jpg'},
    {id: 2, clase: "Vinos", producto: "Vino", tipo: "Malbec", desc: "Luigi Bosca Malbec Vino Tinto 750ml", precio: 1520, img: 'img/productos/02.jpg'},
    {id: 3, clase: "Vinos", producto: "Vino", tipo: "Malbec", desc: "Vino Trumpeter Malbec 750ml", precio: 1180, img: 'img/productos/03.jpg'},
    {id: 4, clase: "Vinos", producto: "Vino", tipo: "Malbec", desc: "Rutini Malbec Vino Tinto 750m", precio: 2680, img: 'img/productos/04.jpg'},
    {id: 5, clase: "Vinos", producto: "Vino", tipo: "Cabernet Sauvignon", desc: "Rutini Cabernet Sauvignon Vino Tinto 750m", precio: 2580, img: 'img/productos/05.jpg'},
    {id: 6, clase: "Vinos", producto: "Vino", tipo: "Blanco", desc: "Vino Blanco Norton Cosecha Tardía 750 Ml", precio: 650, img: 'img/productos/06.jpg'},
    {id: 7, clase: "Vinos", producto: "Vino", tipo: "Blanco", desc: "Vino blanco Torrontés Cafayate bodega Etchart 750 ml", precio: 530, img: 'img/productos/07.jpg'},
    {id: 8, clase: "Vinos", producto: "Vino", tipo: "Blanco", desc: "Vino Blanco Rutini 750 Ml Botella", precio: 3600, img: 'img/productos/08.jpg'},
    {id: 9, clase: "Espirituosas", producto: "Gin", tipo: "London Dry", desc: "Gin Bombay Sapphire London Dry 750 mL", precio: 6000, img: 'img/productos/09.jpg'},
    {id: 10, clase: "Espirituosas", producto: "Gin", tipo: "Blood Orange", desc: "Gin Beefeater Blood Orange Edición Limitada", precio: 3590, img: 'img/productos/10.jpg'},
    {id: 11, clase: "Espirituosas", producto: "Gin", tipo: "London Dry", desc: "Gin Heraclito Macedonio London Dry Botanic 750ml", precio: 2160, img: 'img/productos/11.jpg'},
    {id: 12, clase: "Espirituosas", producto: "Vodka", tipo: "Bebida Blanca", desc: "Vodka Sernova 700ml Fratelli Branca", precio: 900, img: 'img/productos/12.jpg'},
    {id: 13, clase: "Espirituosas", producto: "Vodka", tipo: "Bebida Blanca", desc: "Vodka Skyy 750 Ml Clasico Original", precio: 840, img: 'img/productos/13.jpg'},
    {id: 14, clase: "Espirituosas", producto: "Vodka", tipo: "Bebida Blanca", desc: "Absolut Vodka Pears Pera 750 Ml", precio: 3240, img: 'img/productos/14.jpg'},
    {id: 15, clase: "Espirituosas", producto: "Vodka", tipo: "Bebida Blanca", desc: "Vodka Smirnoff 700ml Original Clasico", precio: 1090, img: 'img/productos/15.jpg'},
    {id: 16, clase: "Espirituosas", producto: "Vodka", tipo: "Bebida Blanca", desc: "Vodka Absolut Azul Clasic Importado Original 750 Ml", precio: 2970, img: 'img/productos/16.jpg'},
    {id: 17, clase: "Aperitivos", producto: "Gancia", tipo: "Gancia", desc: "Gancia Americano Aperitivo Botella 950 Ml", precio: 675, img: 'img/productos/17.jpg'},
    {id: 18, clase: "Aperitivos", producto: "Campari", tipo: "Campari", desc: "Campari Aperitivo 750 Ml Botella", precio: 865, img: 'img/productos/18.jpg'},
    {id: 19, clase: "Aperitivos", producto: "Fernet", tipo: "Fernet", desc: "Fernet Branca 750 Ml", precio: 1260, img: 'img/productos/19.jpg'},
    {id: 20, clase: "Aperitivos", producto: "Martini", tipo: "Martini", desc: "Martini Bianco 1 Litro Aperitivo Botella", precio: 690, img: 'img/productos/20.jpg'},
    {id: 21, clase: "Aperitivos", producto: "Aperol", tipo: "Aperol", desc: "Aperol Aperitivo Italiano 750 Ml", precio: 945, img: 'img/productos/21.jpg'},
    {id: 22, clase: "Aperitivos", producto: "Cinzano", tipo: "Cinzano", desc: "Cinzano Rosso 950 Ml Aperitivo Botella", precio: 660, img: 'img/productos/22.jpg'},
    {id: 23, clase: "Cervezas", producto: "Quilmes", tipo: "Rubia", desc: "Cerveza Quilmes 0.0% Sin alcohol rubia sin alcohol lata 473 mL", precio: 207, img: 'img/productos/23.jpg'},
    {id: 24, clase: "Cervezas", producto: "Andes", tipo: "Roja", desc: "Cerveza Andes Origen Roja Vienna Lager roja lata 473 mL", precio: 216, img: 'img/productos/24.jpg'},
    {id: 25, clase: "Cervezas", producto: "Temple", tipo: "Rubia", desc: "Cerveza Temple Honey rubia lata 473 mL", precio: 306, img: 'img/productos/25.jpg'},
    {id: 26, clase: "Cervezas", producto: "Temple", tipo: "IPA", desc: "Cerveza Temple Wolf IPA rubia lata 473 Ml", precio: 306, img: 'img/productos/26.jpg'},
    {id: 27, clase: "Cervezas", producto: "Quilmes", tipo: "Rubia", desc: "Cerveza Quilmes Clásica American Adjunct Lager rubia lata 473 mL", precio: 220, img: 'img/productos/27.jpg'},
    {id: 28, clase: "Cervezas", producto: "Quilmes", tipo: "Rubia", desc: "Cerveza Imperial Golden Lata 473 Ml", precio: 252, img: 'img/productos/28.jpg'},
    {id: 29, clase: "Cervezas", producto: "Patagonia", tipo: "Pilsener", desc: "Cerveza Patagonia Bohemian Pilsener Lata 410 Ml", precio: 306, img: 'img/productos/29.jpg'},
]